version: "3.5"
services:
  nginx:
    image: nginx
    volumes:
      - ./public:/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php-fpm
    networks:
      - games-searcher-network
    depends_on:
      - php-fpm
    container_name: "nginx-${APP_NAME}"
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www
      - ./docker/php-fpm/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - games-searcher-network
    depends_on:
      - mysql
    container_name: "php-fpm-${APP_NAME}"
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      SERVICE_NAME: "${DB_CONNECTION}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    hostname: mysql
    networks:
      - games-searcher-network
    container_name: "mysql-${APP_NAME}"

networks:
  games-searcher-network:
    driver: bridge
    ipam:
      driver: default
